### ISSUE TITLE
Real world use cases (food for thought)

### ISSUE THREAD

**Issue by brandonros** [marekjm/issue#7]
A more common workflow for what I have seen working at a large corporate company is:

you don't open your own issues. the issues are opened for you, then assigned to you.

then, you move the issues through different statuses:

selected for development

in progress

ready for retest

Then, I'd say the biggest flaw I see is... you issues can move back from "ready for retest" to the beginning of the cycle many times.

I'm sure you are very well aware of this. I just wanted to say what an awesome idea/tool this is and let you know what a bummer it is I can't use it. :P

**Comment by marekjm** [comment]
Oh yes, I am aware of the typical corporate programmer workflow as I work inside it almost every day ;-)

Currently, issues opened in `issue` have to "person" type fields:
- who opened an issue
- who closed an issue
There is nothing preventing adding another field, say "worker" (who works on this issue). Same with "status" field, and configuring a workflow (an issue can be moved from state A, only into state B or C). The only thing is... I don't want to. I think the tag system (every issue can have zero or more tags attached) is *much* more flexible. Instead of moving an issue between statuses you re-tag it. The only thing you lose is the "railroad" of a defined workflow. But I'd assume that people on your team would know that they shouldn't push an issue from "In progress" straight into "Production" without pushing it through "Testing" ;-)

The issue *has* been field-tested, though. In a small five-person company. Developers liked it (three of us), management... not so much, for exactly the reasons you stated. But I always imagines `issue` as a developer-first tool, and intentionally left more "corporate" and manager-oriented features out. However, you can for the code and add anything you need to it (it's GPL!).

Have a nice day, and thanks for reaching out :-)
